langauge: python
python: "3.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
install:
- conda create -n testenv python=3.6 pip pytest
- source activate testenv
- conda install -c conda-forge r-base=3.6.1 r-lme4=1.1_21 r-lmertest=3.1_0 r-emmeans=1.3.5.1 rpy2=3.1.0
- conda install libgfortran
- pip install -r requirements.txt
- python setup.py install
script:
- py.test
